#etcd的地址，如有多个用逗号分隔
etcd:
  server: ${etcdServer:http://172.30.1.228:2379}
#  server: ${etcdServer:https://127.0.0.1:2379}
spring:
  application:
    name: persona-api
  ###############################---redis---##############################
  redis:
    host: ${REDIS_HOST:172.30.1.228}
    port: ${REDIS_PORT:16379}
    password: ${REDIS_PASSWORD:}
server:
  port: 9999